### ISSUE TITLE
Context should be stored as .json file

### ISSUE THREAD

**Issue by jpsfs** [criticalmanufacturing/dev-tasks#2]
**I'm submitting a ...**  
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

**Current behavior**
Currently context variables are defined inside javascript files. This forces tools like https://github.com/criticalmanufacturing/generator-html to change cmf.dev.tasks files directory.

**Expected behavior**
cmf.dev.tasks should look for a .cmf.dev.tasks.json (proposed name, can be different) on the root of the repository. Values on this file override the default ones from cmf.dev.tasks.

**What is the motivation / use case for changing the behavior?**
Make project setup easier and repeatable. Avoiding to have to perform multiple times the same operation (one for each developer on the team).

**Please tell us about your environment:**

* **CMF Product version:** >= 5.0

* **Browser:** [NA]

 
* **Language:** all

* **Node:** `node --version` =  [all]

**Comment by soulcorrosion** [comment]
This is a side effect from moving the cmf.dev.tasks to npm. The approach of using a .json file was already used in other situations, so here I see no reason to do differently. The name is actually not bad because it gives us the clear feeling that this file is important to someone, whereas a completely different name can raise questions.
